

ALTER TABLE ONLY ANTOption.b3log.B3SignalLogger ALTER COLUMN negocios TYPE INTEGER, ALTER COLUMN negocios SET NOT NULL;

ALTER TABLE ONLY ANTOption.b3log.B3SignalLogger ALTER COLUMN oferta_compra TYPE REAL, ALTER COLUMN oferta_compra SET NOT NULL;

ALTER TABLE ONLY ANTOption.b3log.B3SignalLogger ALTER COLUMN oferta_venda TYPE REAL, ALTER COLUMN oferta_venda SET NOT NULL;

ALTER TABLE ONLY ANTOption.b3log.B3SignalLogger ALTER COLUMN ultimo TYPE REAL, ALTER COLUMN ultimo SET NOT NULL;
